# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.1
- 3.2
- oldrel
- release

include:
  matrix:
    r: devel
warnings_are_errors: false
