# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr
  - devtools
  - roxygen2

bioc_required: true

r:
- 3.4
- oldrel
- devel
- release

warnings_are_errors: false

after_success:
- Rscript -e 'library(covr);codecov()'

env: _R_CHECK_CRAN_INCOMING_=FALSE

