---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
suppressMessages(devtools::load_all("."))
```

# Verissimo r-package

With personal functions I like to reuse everytime!

## Proper

One of such is a proper function that capitalizes a string.

```{r proper}
x <- "OnE oF sUcH iS a proPer function that capitalizes a string."
proper(x)
```

## my.colors & my.symbols & draw.empty.plot

`my.colors()` and `my.symbols()` can be used to improve plot readability.

In this example, draw.empty.plot is also used to create an empty plot to show data points after.

```{r mycolors}
xdata <- -10:10
draw.empty.plot(xlim = c(min(xdata),max(xdata)), ylim = c(0,23))
for (ix in 1:22) {
  points(xdata, 1/10 * xdata * xdata + ix, pch = my.symbols(ix), col = my.colors(ix), cex = .9)
}
```

## draw.kaplan

```{r draw.kaplan}
suppressPackageStartupMessages(library(survival))
suppressPackageStartupMessages(library(plyr))
suppressPackageStartupMessages(library(ggfortify))
suppressPackageStartupMessages(library(gridExtra))
data(flchain)
ydata <- data.frame( time = flchain$futime, status = flchain$death)
xdata <- cbind(flchain$age, as.numeric(flchain$sex == 'M'))
page <- draw.kaplan(list(Age= c(1,0)), xdata = xdata, ydata = ydata)$plot
psex <- draw.kaplan(list(Age= c(0,1)), xdata = xdata, ydata = ydata)$plot
grid.arrange(page, psex, ncol = 2)
#
draw.kaplan(list(Age= c(1,0), Sex = c(0,1)), xdata = xdata, ydata = ydata)$plot
```

