#' Constants for 'loose.rock' package
#'
#' Log level constants and the logger options.
#'
#' The logging configuration is managed by 'loose.rock.options', a function
#' generated by OptionsManager within 'futile.options'.
#'
#' @name loose.rock.options
#' @usage loose.rock.options(..., simplify = FALSE, update = list())
#' @param ... TODO
#' @param simplify TODO
#' @param update TODO
#' @author André Veríssimo
#' @seealso \code{futile.options}
#' @keywords data
loose.rock.options <- OptionsManager('loose.rock', default = list(base.dir = tempdir.cache(), show.message = TRUE))

#' change base.dir for run.cache
#'
#' @param path to base directory where cache is saved
#'
#' @return
#' @export
#'
#' @examples
#' base.dir('/tmp/cache')
base.dir <- function(path = NULL) {
  if (!is.null(path))
    loose.rock.options(update = list('base.dir', path))
  return(loose.rock.options('base.dir'))
}

#' Show messages option in run.cache
#'
#' @param show.message boolean indicating to show messages or not
#'
#' @return
#' @export
#'
#' @examples
#' show.message(FALSE)
show.message <- function(show.message = NULL) {
  if (!is.null(show.message))
    loose.rock.options(update = list('show.message', show.message))
  return(loose.rock.options('show.message'))
}
