#' Constants for 'verissimo'
#'
#' Log level constants and the logger options.
#'
#' The logging configuration is managed by 'verissimo.options', a function
#' generated by OptionsManager within 'futile.options'.
#'
#' @name verissimo.options
#' @usage verissimo.options(..., simplify = FALSE, update = list())
#' @param ... TODO
#' @param simplify TODO
#' @param update TODO
#' @author Brian Lee Yung Rowe
#' @seealso \code{futile.options}
#' @keywords data
verissimo.options <- OptionsManager('verissimo.options', default = list(base.dir = verissimo::tempdir.cache(), show.message = TRUE))

#' Title
#'
#' @param path
#'
#' @return
#' @export
#'
#' @examples
base.dir <- function(path = NULL) {
  if (!is.null(path))
    verissimo.options(update = list('base.dir', path))
  return(verissimo.options('base.dir'))
}

#' Title
#'
#' @param path
#'
#' @return
#' @export
#'
#' @examples
show.message <- function(show.message = NULL) {
  if (!is.null(show.message))
    verissimo.options(update = list('show.message', show.message))
  return(verissimo.options('show.message'))
}
